### ISSUE TITLE
Check alternatives to python MySQLdb

### ISSUE THREAD

**Issue by matteodefelice** [ClaudioR3/workspace#1]
Controlla questo: http://stackoverflow.com/questions/372885/how-do-i-connect-to-a-mysql-database-in-python

e questa risposta: http://stackoverflow.com/questions/372885/how-do-i-connect-to-a-mysql-database-in-python/20959654#20959654

Se si vuole massimizzare l'uso del tool bisogna minimizzare i requisiti per l'installazione.

**Comment by ClaudioR3** [comment]
Come da lei richiesto ho cambiato da MySQLdb a mysql.connector di python.

**Comment by matteodefelice** [comment]
Ok, appena è pronta una guida per l'installazione con l'elenco dei pacchetti da installare e le cose da fare, lo installo su un computer nuovo,
