### ISSUE TITLE
Error with find

### ISSUE THREAD

**Issue by matteodefelice** [ClaudioR3/workspace#4]
La configurazione funziona, però ho ottenuto questo:

```
New-MBP-2:src matteodefelice$ python Sagitta.py find -VariableName rsds
descriptor 'lower' requires a 'str' object but received a 'unicode'
```

**Comment by ClaudioR3** [comment]
Risolto e ho anche tolto la possibilità di inserire VariableName tas ( adesso solleva un'eccezione)

**Comment by matteodefelice** [comment]
Il problema rimane!

**Comment by ClaudioR3** [comment]
Io non lo riscontro più il problema nella stessa operazione :
python Sagitta.py find -VariableName rsds
Ripropone proprio l'esatto errore?

**Comment by matteodefelice** [comment]
Ho cancellato e riclonato il repository ed ora funziona!
